In [1]:
!git clone https://github.com/AshishJangra27/datasets

Cloning into 'datasets'...
remote: Enumerating objects: 328, done.
remote: Counting objects: 100% (93/93), done.
remote: Compressing objects: 100% (83/83), done.
remote: Total 328 (delta 19), reused 54 (delta 9), pack-reused 235 (from 1)
Receiving objects: 100% (328/328), 278.62 MiB | 16.58 MiB/s, done.
Resolving deltas: 100% (145/145), done.
Updating files: 100% (225/225), done.

In [57]:
import pandas as pd

df = pd.read_csv('/content/datasets/Airbnb/airbnb.csv')
df.head()

,id,name,rating,reviews,host_name,host_id,address,features,amenities,safety_rules,hourse_rules,img_links,price
0,49849504,Perla bungalov,4.71,64,Entire bungalow hosted by Mehmetcan,357334205.0,"Kartepe, Kocaeli, Turkey","2 guests,2 bedrooms,1 bed,1 bathroom","Mountain view,Valley view,Lake access,Kitchen,...","󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...","Check-in: Flexible,Check out: 12:00 pm,Pets ar...",https://a0.muscache.com/im/pictures/a5da5cb7-c...,"₹8,078 per night"
1,50891766,Authentic Beach Architect Sheltered Villa with...,New,NaN,Entire villa hosted by Fatih,386223873.0,"Kaş, Antalya, Turkey","4 guests,2 bedrooms,2 beds,2 bathrooms","Kitchen,Wifi,Dedicated workspace,Free parking ...","󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...","Check-in: 4:00 pm - 11:00 pm,Check out: 10:00 ...",https://a0.muscache.com/im/pictures/61b70855-2...,"₹4,665 per night"
2,50699164,cottages sataplia,4.85,68,Entire cabin hosted by Giorgi,409690853.0,"Imereti, Georgia","4 guests,1 bedroom,3 beds,1 bathroom","Mountain view,Kitchen,Wifi,Dedicated workspace...","󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...","Check-in: After 1:00 pm,Check out: 12:00 pm,Se...",https://a0.muscache.com/im/pictures/miso/Hosti...,"₹5,991 per night"
3,49871422,Sapanca Breathable Bungalow,5.0,13,Entire bungalow hosted by Melih,401873242.0,"Sapanca, Sakarya, Turkey","4 guests,1 bedroom,2 beds,1 bathroom","Mountain view,Valley view,Kitchen,Wifi,Free pa...","󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...","Check-in: After 2:00 pm,Check out: 12:00 pm,No...",https://a0.muscache.com/im/pictures/72e6396e-e...,"₹11,339 per night"
4,51245886,Bungalov Ev 2,New,NaN,Entire bungalow hosted by Arp Sapanca,414884116.0,"Sapanca, Sakarya, Turkey","2 guests,1 bedroom,1 bed,1 bathroom","Kitchen,Wifi,Free parking on premises,TV,Air c...","󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...","Check-in: After 2:00 pm,Check out: 12:00 pm,No...",https://a0.muscache.com/im/pictures/73973308-e...,"₹6,673 per night"

In [58]:
del df['img_links']
del df['host_id']

df.isnull().sum()

id                 0
name               1
rating             0
reviews         2744
host_name          1
address           27
features          27
amenities        989
safety_rules     209
hourse_rules     209
price              0
dtype: int64

In [59]:
df = df.dropna(subset=['name','address','safety_rules'])

df.isnull().sum()

df['amenities'].fillna(df['amenities'].mode()[0], inplace=True)

<ipython-input-59-91efe9fdd5f6>:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['amenities'].fillna(df['amenities'].mode()[0], inplace=True)
<ipython-input-59-91efe9fdd5f6>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['amenities'].fillna(df['amenities'].mode()[0], inplace=True)

In [60]:
df.dropna(subset=['name','address','safety_rules']).isnull().sum()

id                 0
name               0
rating             0
reviews         2630
host_name          0
address            0
features           0
amenities          0
safety_rules       0
hourse_rules       0
price              0
dtype: int64

In [61]:
df['reviews'] = df['reviews'].fillna('0')

df.dropna(subset=['name','address','safety_rules']).isnull().sum()

id              0
name            0
rating          0
reviews         0
host_name       0
address         0
features        0
amenities       0
safety_rules    0
hourse_rules    0
price           0
dtype: int64

In [62]:
df[df['rating'] != 'New'].isnull().sum()

id              0
name            0
rating          0
reviews         0
host_name       0
address         0
features        0
amenities       0
safety_rules    0
hourse_rules    0
price           0
dtype: int64

In [63]:
df['amenities']

0        Mountain view,Valley view,Lake access,Kitchen,...
1        Kitchen,Wifi,Dedicated workspace,Free parking ...
2        Mountain view,Kitchen,Wifi,Dedicated workspace...
3        Mountain view,Valley view,Kitchen,Wifi,Free pa...
4        Kitchen,Wifi,Free parking on premises,TV,Air c...
                               ...
14451    Kitchen,Wifi,Free parking on premises,Private ...
14452    Wifi,Free on-street parking,Air conditioning,G...
14453    Wifi,Breakfast,Long-term stays allowed,Unavail...
14454    Kitchen,Wifi,Dedicated workspace,Free parking ...
14455    Sea view,Beach access – Beachfront,Kitchen,Wif...
Name: amenities, Length: 14247, dtype: object

In [66]:
for i in df['features'][:10]:
  print(i)

2 guests,2 bedrooms,1 bed,1 bathroom
4 guests,2 bedrooms,2 beds,2 bathrooms
4 guests,1 bedroom,3 beds,1 bathroom
4 guests,1 bedroom,2 beds,1 bathroom
2 guests,1 bedroom,1 bed,1 bathroom
2 guests,1 bedroom,2 beds,1 bathroom
2 guests,1 bedroom,1 bed,1 bathroom
8 guests,1 bedroom,2 beds,1 bathroom
2 guests,1 bedroom,1 bed,1 bathroom
10 guests,4 bedrooms,6 beds,3 bathrooms

In [81]:
guests = []

for i in df['features']:

  flag = False

  for j in i.split(','):
    if 'guest' in j:
      flag = True
      guests.append(int(j.split(' ')[0]))

  if flag == False:
    guests.append(0)

df['guests'] = guests

df.head()

,id,name,rating,reviews,host_name,address,features,amenities,safety_rules,hourse_rules,price,guests
0,49849504,Perla bungalov,4.71,64,Entire bungalow hosted by Mehmetcan,"Kartepe, Kocaeli, Turkey","2 guests,2 bedrooms,1 bed,1 bathroom","Mountain view,Valley view,Lake access,Kitchen,...","󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...","Check-in: Flexible,Check out: 12:00 pm,Pets ar...","₹8,078 per night",2
1,50891766,Authentic Beach Architect Sheltered Villa with...,New,0,Entire villa hosted by Fatih,"Kaş, Antalya, Turkey","4 guests,2 bedrooms,2 beds,2 bathrooms","Kitchen,Wifi,Dedicated workspace,Free parking ...","󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...","Check-in: 4:00 pm - 11:00 pm,Check out: 10:00 ...","₹4,665 per night",4
2,50699164,cottages sataplia,4.85,68,Entire cabin hosted by Giorgi,"Imereti, Georgia","4 guests,1 bedroom,3 beds,1 bathroom","Mountain view,Kitchen,Wifi,Dedicated workspace...","󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...","Check-in: After 1:00 pm,Check out: 12:00 pm,Se...","₹5,991 per night",4
3,49871422,Sapanca Breathable Bungalow,5.0,13,Entire bungalow hosted by Melih,"Sapanca, Sakarya, Turkey","4 guests,1 bedroom,2 beds,1 bathroom","Mountain view,Valley view,Kitchen,Wifi,Free pa...","󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...","Check-in: After 2:00 pm,Check out: 12:00 pm,No...","₹11,339 per night",4
4,51245886,Bungalov Ev 2,New,0,Entire bungalow hosted by Arp Sapanca,"Sapanca, Sakarya, Turkey","2 guests,1 bedroom,1 bed,1 bathroom","Kitchen,Wifi,Free parking on premises,TV,Air c...","󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...","Check-in: After 2:00 pm,Check out: 12:00 pm,No...","₹6,673 per night",2

In [80]:
len(df)

14247

In [ ]:
- No of bedroom (Int)
- No of beds    (Int)
- No of baths   (Int)
- No of guests  (Int)
- Kitchen       (Int)
- Food Service (Bool)
- Bar           (True/False)
- Wifi          (True/False)
- TV            (True/False)
- Carpet Area   (Int)
- Swimming Pool (True/False)

# - Views         (String, Categorical)
# - Architecture  (String, Categorical)
# - Type of Property (String, Categorical)